### PR TITLE
Update request dep

### PR DESCRIPTION
**Pull request by pdehaan**
See mikeal/request#993

### CODE REVIEW

**Comment by robertkowalski** [comment]
Thanks!

Btw. please don't use the GitHub online editor for PRs in the future, the dependency `request` is a checked in part of this repository. Additionally your email is shown as `pdehaan@users.noreply.github.com`

**Comment by robertkowalski** [comment]
landed on master as a378a98cd92d5e804cb62a7afce238e42480d563 and published as 1.0.0 - thanks again!

**Comment by pdehaan** [comment]
Curious, what's wrong with the online GitHub editor for PRs?
It's a lot easier than actually cloning a repo for simple 1-line changes.

**Comment by robertkowalski** [comment]
Let me try to explain: the email of the author is not the original email of the author (yours got changed to `pdehaan@users.noreply.github.com` by using the online editor) and as `request` is checked in for this standalone application, an update of the `node_modules` folder was not possible. I did that in https://github.com/robertkowalski/ai/commit/edfd24db9d37f8b90b9c777a6a4fd912cf63a694

I saw some PR previously which were using the GH editor which had problems with generated content: like an `npm install` with checked in modules or a webserver with checked-in bower components. Or where something other that is checked in has to be generated, let's say docs, code or images. This mostly led to a short pingpong between my colleagues and the person which opened the PR. That made me sad, as we don't have much time and it costed us time again once the issue was resolved. Over the time I got the personal feeling that this happens more often with the online editor.

**Comment by pdehaan** [comment]
@robertkowalski Wow, thanks for the info.

Not sure if the "noreply" is solely due to the fact that I used the online editor, versus the fact that you can choose to not share your email address in https://github.com/settings/emails

> **Keep my email address private**
> We will use **pdehaan@users.noreply.github.com** when performing Git operations and sending email on your behalf.

&mdash; See https://help.github.com/articles/keeping-your-email-address-private

**Pull request closed without merging**
